== Работа в IAR Embedded Workbench
== Задание

Целью данной практической работы было создание кода программы,
который бы по нажатию кнопки менял состояние четырёх светодиодов на противополжные.
Также нужно тактироваться от частоты _10 МГц_ (или около _10 МГц_).


== Настройка частоты
Первым делом нужно было поработать с частотой. Включаем источник частоты *HSE*, ждём
пока он будет готов,
далее выбираем *HSE* как как источник тактирования, выключаем *HSI*, в конфигурации *PLL*
ставим *HSE* как источник и производим
вычисления.

Так как на *HSE* у нас _8 МГц_, то для того, чтобы получить на выходе
значение близкое к _10 МГц_, нам нужно
произвести следующие действия:

 8 МГц / 4 МГц = 2 МГц
 2 МГц * 50 МГц = 100 МГц
 100 МГц / 6 МГц = 16 МГц


[source, cpp]
----
RCC::CR::HSEON::On::Set();
  while(!RCC::CR::HSERDY::Ready::IsSet())
  {
  }
  RCC::CFGR::SW::Hse::Set();
  while(!RCC::CFGR::SWS::Hse::IsSet())
  {
  }
  RCC::CR::HSION::Off::Set();
  RCC::PLLCFGR::PLLSRC::HseSource::Set();
  RCC::PLLCFGR::PLLM0::Set(4U); // 8 MHz / 4 MHz = 2 MHz
  RCC::PLLCFGR::PLLN0::Set(50U); // 2 MHz * 50 MHz = 100 MHz (так как значения должны быть от 100 MHz до 432 MHz)
  RCC::PLLCFGR::PLLP0::Pllp6::Set(); // 100 MHz / 6 = 16 MHz
  RCC::CR::PLLON::On::Set();
  while(RCC::CR::PLLRDY::Unlocked::IsSet())
  {
  }
  RCC::CFGR::SW::Pll::Set();
  while(!RCC::CFGR::SWS::Pll::IsSet())
  {
  }
----

В ходе работы столкнулись с проблемой: Мы не смогли тактироваться от частоты, которая была бы
меньше _15 МГц_. Вручную, с помощью делителей были произведены многочисленные опыты по подбору
нижнего значения частоты. Самым минимальным из этих значений оказалось значение _16 МГц_.

== Работа с шаблонами

_**Шаблоны** (англ. *template*) — средство языка *C++*, предназначенное для кодирования
обобщённых алгоритмов, без привязки к некоторым параметрам
(например, типам данных, размерам буферов, значениям по умолчанию)._

В **C++ ** возможно создание шаблонов функций и классов.

_Шаблоны позволяют создавать параметризованные классы и функции.
Параметром может быть любой тип или значение одного из допустимых
типов (целое число, enum, указатель на любой объект с глобально доступным именем, ссылка)._

Чтобы получить структуру следующего вида нам нужно поработать с классами.

[source, cpp]
----
int main()
{
    // Здесь надо настроить PLL на 10 Мгц от внешнего источника и переключить его на системную частоту

  for(;;)
  {
  if(UserButton::IsPressed())
  {
    Leds::Toggle();
  }
  }
  // кнопка находится на порту PORTC.13
  // светодиоды на порту PC.9, PC.8, PC.5, PA.5
  // Задание По нажатию кнопки переключать все
  // 4 светодиода в противоположное состояние
  return 1 ;
}
----



Создадим 4 класса:

- *Port* - отвечает за работу с портом ( вместо *T* будем передавать значения портов: *GPIOA*, *GPOIC* и т.д.);
- *Pin* - отвечает за переключение одной ножки;
- *Button* - отвечает за переключение кнопки;
- *Leds* - за работу со светодиодами.


[source, cpp]
----
template<typename T> // Данный класс отвечает за работу с портом ( вместо T будем передавать значения портов: GPIOA, GPOIC и т.д.)
struct Port
{
  static void Set(std::uint32_t value)
  {
    T::BSSR::Write(value);
  }

  static void Reset(std::uint32_t value)
  {
    T::BSSR::Write(value << 16U);
  }

  static void Toggle(std::uint32_t value)
  {
    T::ODR::Toggle(value);
  }

  static auto Get()
  {
    return T::IDR::Get();
  }

};

template<typename Port, uint8_t pinNum>  // Данынй класс отвечает за переключение одной ножки
struct Pin
{
  static void Set()
  {
    Port::Set(1U << pinNum);
  }

  static void Reset()
  {
    Port::Reset(1U << pinNum);
  }

  static void Toggle()
  {
    Port::Toggle(1U << pinNum);
  }

  static auto IsSet()
  {
    return ((Port::Get() & (1U << pinNum)) != 0 );
  }


};

template<typename Pin>  // Данынй класс отвечает за переключение кнопки
struct Button
{
   static auto IsPressed()
  {
    if(!Pin::IsSet())
    {
      while(!Pin::IsSet())
      {

      }
      return true;
    }

    return false;

  }
};

template<typename ... Tleds> // Данный класс отвечает за работу с индикаторами
struct Leds
{
   static void Toggle()
  {
    (Tleds::Toggle(),...);
  }
};

----



В каждом классе описаны определенные функции, которые приведены на рисунках ниже:


Также дополнительно была создана функция *Delay*:

[source, cpp]
----
void Delay()
    {
    for(int i = 0; i < 1000000; i++)
    {
    }
}
----

Затем, с помощью *using*, введём пользовательские типы:

[source, cpp]
----
using ButtonPin = Pin<Port<GPIOC>, 13>; // Вводим польовательский тип, который равен пину (Gpioc, 13)
using UserButton = Button<ButtonPin>;

using LED1 = Pin<Port<GPIOC>, 5>;
using LED2 = Pin<Port<GPIOC>, 8>;
using LED3 = Pin<Port<GPIOC>, 9>;
using LED4 = Pin<Port<GPIOA>, 5>;
using MyLeds = Leds<LED1, LED2, LED3, LED4>;
----


Полученный код имеет следующий вид:


[source, cpp]
----
int main()
{
RCC::CR::HSEON::On::Set();
while(!RCC::CR::HSERDY::Ready::IsSet())
{
}
RCC::CFGR::SW::Hse::Set();
while(!RCC::CFGR::SWS::Hse::IsSet())
{
}
RCC::CR::HSION::Off::Set();
RCC::PLLCFGR::PLLSRC::HseSource::Set();
RCC::PLLCFGR::PLLM0::Set(4U); // 8 MHz / 4 MHz = 2 MHz
RCC::PLLCFGR::PLLN0::Set(50U); // 2 MHz * 50 MHz = 100 MHz (так как значения должны быть от 100 MHz до 432 MHz)
RCC::PLLCFGR::PLLP0::Pllp6::Set(); // 100 MHz / 6 = 16 MHz
RCC::CR::PLLON::On::Set();
while(RCC::CR::PLLRDY::Unlocked::IsSet())
{
}
RCC::CFGR::SW::Pll::Set();
while(!RCC::CFGR::SWS::Pll::IsSet())
{
}
RCC::AHB1ENR::GPIOCEN::Enable::Set();
RCC::AHB1ENR::GPIOAEN::Enable::Set();
GPIOC::MODER::MODER13::Input::Set();
GPIOC::MODER::MODER5::Output::Set();
GPIOC::MODER::MODER8::Output::Set();
GPIOC::MODER::MODER9::Output::Set();
GPIOA::MODER::MODER5::Output::Set();

  for(;;)
    {
    if(UserButton::IsPressed())
    {
      MyLeds::Toggle();
    }

    Delay();
   }
}
----

Запустим программу и посмотрим на результат. Мы получили, что при нажатии кнопки,
у нас включаются все четыре светодиода. Результат в формате *gif* лежит в папке *Photo*.

